// SPDX-License-Identifier: GPL-3.0-or-later
//! Colors and text, generated from the shared palette.
//!
//! [`palette`] is generated by `wlrix-assets/tools/palettegen` from the same JSON the
//! compositor, the greeter and the Avalonia theme are built from, so every part of wlRIX
//! renders the same Indigo Magic. Edit the JSON and re-run `just palette`; never edit the
//! generated file.

// The palette is emitted whole, and not every constant has a caller yet.
#![allow(dead_code)]

pub mod font;
pub mod palette;

/// A color, packed as native-endian ARGB.
///
/// Packed rather than four bytes because the canvas is a `&mut [u32]` over a `wl_shm`
/// `Argb8888` buffer: a fill is then one store per pixel with no reassembly.
///
/// Kept byte-identical to the greeter's `theme::Rgb` deliberately -- both draw the same
/// Motif chrome into the same buffer format, and the two should stay swappable if they are
/// ever pulled into a shared `wlrix-ui` crate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb(pub u32);

impl Rgb {
    /// The color's channels, for blending coverage against a background.
    pub fn channels(self) -> (u8, u8, u8) {
        let [_, r, g, b] = self.0.to_be_bytes();
        (r, g, b)
    }

    /// Mix towards `other` by `amount` (0 = unchanged, 255 = fully `other`).
    ///
    /// This is what turns an icon's or a glyph's coverage into pixels: the canvas is
    /// opaque, so a plain interpolation is right and there is no premultiplied alpha to
    /// get wrong.
    pub fn blend(self, other: Rgb, amount: u8) -> Rgb {
        let (r0, g0, b0) = self.channels();
        let (r1, g1, b1) = other.channels();
        let mix = |from: u8, to: u8| -> u32 {
            let (from, to) = (i32::from(from), i32::from(to));
            (from + (to - from) * i32::from(amount) / 255) as u32
        };
        Rgb(0xff00_0000 | (mix(r0, r1) << 16) | (mix(g0, g1) << 8) | mix(b0, b1))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BLACK: Rgb = Rgb(0xff00_0000);
    const WHITE: Rgb = Rgb(0xffff_ffff);

    #[test]
    fn channels_unpack_argb() {
        assert_eq!(Rgb(0xff_5680ab).channels(), (0x56, 0x80, 0xab));
    }

    #[test]
    fn blending_by_the_extremes_is_exact() {
        // An icon at zero coverage must leave the desktop untouched, and at full coverage
        // must be its tint exactly -- any drift shows as a halo around every icon.
        assert_eq!(BLACK.blend(WHITE, 0), BLACK);
        assert_eq!(BLACK.blend(WHITE, 255), WHITE);
        assert_eq!(WHITE.blend(BLACK, 255), BLACK);
    }

    #[test]
    fn blending_stays_opaque_and_in_range() {
        for amount in [0u8, 1, 64, 128, 200, 254, 255] {
            let mixed = BLACK.blend(WHITE, amount);
            assert_eq!(mixed.0 >> 24, 0xff, "alpha lost at {amount}");
            let (r, _, _) = mixed.channels();
            assert_eq!(r, amount, "channel should track coverage at {amount}");
        }
    }
}
