// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the
// palette JSON in wlrix-assets/palette/ and re-run `just palette`.
#![allow(dead_code)]

use super::Rgb;

/// `#555555`
pub const DESKTOP: Rgb = Rgb(0xff_555555);

/// `#aaaaaa`
pub const ICON_TINT: Rgb = Rgb(0xff_aaaaaa);

/// `#ffffff`
pub const ICON_TINT_HOVER: Rgb = Rgb(0xff_ffffff);

/// `#ffff00`
pub const ICON_TINT_SELECTED: Rgb = Rgb(0xff_ffff00);

/// `#ffffff`
pub const ICON_LABEL: Rgb = Rgb(0xff_ffffff);

/// `#000000`
pub const ICON_LABEL_SELECTED: Rgb = Rgb(0xff_000000);

/// `#000000`
pub const OUTER_LINE: Rgb = Rgb(0xff_000000);

/// `#999999`
pub const FACE: Rgb = Rgb(0xff_999999);

/// `#e5e5e5`
pub const FACE_TOP_SHADOW: Rgb = Rgb(0xff_e5e5e5);

/// `#545454`
pub const FACE_BOTTOM_SHADOW: Rgb = Rgb(0xff_545454);

/// `#000000`
pub const FOREGROUND: Rgb = Rgb(0xff_000000);

/// `#a59f80`
pub const MENU_HIGHLIGHT: Rgb = Rgb(0xff_a59f80);
